-- Script SQL para Supabase Dashboard
-- 1. Crear la tabla
CREATE TABLE IF NOT EXISTS public.most_streamed (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    image_url TEXT NOT NULL,
    order_index INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Habilitar RLS
ALTER TABLE public.most_streamed ENABLE ROW LEVEL SECURITY;

-- 3. Política de lectura pública
CREATE POLICY "Public Read Access" 
ON public.most_streamed 
FOR SELECT 
USING (true);

-- 4. Insertar datos iniciales (Asegúrate de que las imágenes existan en tu R2/Almacenamiento)
INSERT INTO public.most_streamed (title, image_url, order_index)
VALUES 
    ('Overwatch', 'Imagenes/Overwatch.png', 1),
    ('Reanimal', 'Imagenes/Reanimal.png', 2),
    ('Poppy Playtime', 'Imagenes/PoppyPlayTime.png', 3),
    ('Teamfight Tactics', 'Imagenes/TeamfightTactics.png', 4),
    ('GTA V', 'Imagenes/GTA_V.png', 5),
    ('Just Chatting', 'Imagenes/JustCHatting.png', 6);
