import fs from 'fs';

const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms));

const songsList = [
  // === 1. VIDEO GAME SOUNDTRACKS (150 TRACKS) ===
  { name: "Super Mario Bros. - Overworld Theme", search: "Super Mario Bros Overworld Theme" },
  { name: "The Legend of Zelda - Main Theme", search: "The Legend of Zelda Theme" },
  { name: "Tetris - Korobeiniki (Theme A)", search: "Tetris Korobeiniki Theme A" },
  { name: "Minecraft - Sweden", search: "Minecraft Sweden" },
  { name: "Halo - Mjolnir Mix (Main Theme)", search: "Halo Mjolnir Mix" },
  { name: "The Elder Scrolls V: Skyrim - Dragonborn", search: "Skyrim Dragonborn Theme" },
  { name: "Undertale - Megalovania", search: "Undertale Megalovania" },
  { name: "Portal - Still Alive", search: "Portal Still Alive" },
  { name: "Pokemon Red & Blue - Title Theme", search: "Pokemon Theme" },
  { name: "Final Fantasy VII - Aerith's Theme", search: "Final Fantasy VII Aeriths Theme" },
  { name: "Chrono Trigger - Wind Scene", search: "Chrono Trigger Wind Scene" },
  { name: "Grand Theft Auto: San Andreas - Main Theme", search: "GTA San Andreas Theme" },
  { name: "Doom (1993) - At Doom's Gate", search: "Doom At Dooms Gate" },
  { name: "Undertale - Fallen Down", search: "Undertale Fallen Down" },
  { name: "The Legend of Zelda: Ocarina of Time - Gerudo Valley", search: "Zelda Gerudo Valley" },
  { name: "Cuphead - Don't Deal With the Devil", search: "Cuphead Dont Deal With the Devil" },
  { name: "Wii Sports - Theme", search: "Wii Sports Theme" },
  { name: "Kingdom Hearts - Dearly Beloved", search: "Kingdom Hearts Dearly Beloved" },
  { name: "Nier: Automata - Weight of the World", search: "Nier Automata Weight of the World" },
  { name: "Cyberpunk 2077 - Never Fade Away", search: "Cyberpunk 2077 Never Fade Away" },
  { name: "League of Legends - Legends Never Die", search: "Legends Never Die League of Legends" },
  { name: "Assassin's Creed II - Ezio's Family", search: "Assassins Creed Ezios Family" },
  { name: "Civilization IV - Baba Yetu", search: "Civilization IV Baba Yetu" },
  { name: "Persona 5 - Last Surprise", search: "Persona 5 Last Surprise" },
  { name: "Shadow of the Colossus - The Opened Way", search: "Shadow of the Colossus The Opened Way" },
  { name: "Silent Hill 2 - Theme of Laura", search: "Silent Hill 2 Theme of Laura" },
  { name: "Plants vs. Zombies - Loonboon", search: "Plants vs Zombies Loonboon" },
  { name: "Fallout 4 - Main Theme", search: "Fallout 4 Main Theme" },
  { name: "The Witcher 3 - Silver for Monsters", search: "Witcher 3 Silver for Monsters" },
  { name: "Pac-Man - Classic Theme", search: "Pac Man theme" },
  { name: "Angry Birds - Theme", search: "Angry Birds Theme" },
  { name: "Metal Gear Solid 3 - Snake Eater", search: "Metal Gear Solid Snake Eater" },
  { name: "Super Smash Bros. Brawl - Main Theme", search: "Super Smash Bros Brawl Theme" },
  { name: "Genshin Impact - Main Theme", search: "Genshin Impact Theme" },
  { name: "Stardew Valley - Overture", search: "Stardew Valley Overture" },
  { name: "Elder Scrolls III: Morrowind - Call of Magic", search: "Morrowind Call of Magic" },
  { name: "Hollow Knight - Dirtmouth Theme", search: "Hollow Knight Dirtmouth" },
  { name: "Hades - In The Blood", search: "Hades In The Blood" },
  { name: "Red Dead Redemption 2 - Unshaken", search: "Red Dead Redemption 2 Unshaken" },
  { name: "God of War (2018) - Main Theme", search: "God of War 2018 Theme" },
  { name: "World of Warcraft - Legends of Azeroth", search: "World of Warcraft Legends of Azeroth" },
  { name: "Grand Theft Auto IV - Soviet Connection", search: "GTA IV Soviet Connection" },
  { name: "Castlevania - Vampire Killer", search: "Castlevania Vampire Killer" },
  { name: "Street Fighter II - Guile's Theme", search: "Guiles Theme Street Fighter" },
  { name: "Sonic the Hedgehog - Green Hill Zone", search: "Sonic Green Hill Zone" },
  { name: "Mega Man 2 - Dr. Wily's Castle", search: "Mega Man Wily Castle" },
  { name: "Outer Wilds - Main Theme", search: "Outer Wilds Theme" },
  { name: "Among Us - Main Theme", search: "Among Us Theme" },
  { name: "Elden Ring - Main Theme", search: "Elden Ring Theme" },
  { name: "Deus Ex - Main Theme", search: "Deus Ex Theme" },
  { name: "Metroid - Title Theme", search: "Metroid Title Theme" },
  { name: "Mega Man - Elec Man Theme", search: "Mega Man Elec Man" },
  { name: "Castlevania: SotN - Bloody Tears", search: "Castlevania Bloody Tears" },
  { name: "Donkey Kong Country - Aquatic Ambiance", search: "Donkey Kong Aquatic Ambiance" },
  { name: "Mass Effect 3 - Leaving Earth", search: "Mass Effect 3 Leaving Earth" },
  { name: "Crash Bandicoot - Main Theme", search: "Crash Bandicoot Main Theme" },
  { name: "Spyro the Dragon - Main Theme", search: "Spyro the Dragon Theme" },
  { name: "Banjo-Kazooie - Spiral Mountain", search: "Banjo Kazooie Spiral Mountain" },
  { name: "The Legend of Zelda: Wind Waker - Great Sea", search: "Zelda Wind Waker Great Sea" },
  { name: "Uncharted - Nate's Theme", search: "Uncharted Nates Theme" },
  { name: "Detroit: Become Human - Kara's Theme", search: "Detroit Become Human Karas Theme" },
  { name: "The Last of Us - Main Theme", search: "The Last of Us Main Theme" },
  { name: "Kingdom Hearts - Simple and Clean", search: "Simple and Clean Kingdom Hearts" },
  { name: "Minecraft - Wet Hands", search: "Minecraft Wet Hands" },
  { name: "Final Fantasy X - To Zanarkand", search: "Final Fantasy To Zanarkand" },
  { name: "Chrono Cross - Scars of Time", search: "Chrono Cross Scars of Time" },
  { name: "Monster Hunter - Proof of a Hero", search: "Monster Hunter Proof of a Hero" },
  { name: "Gears of War - Main Theme", search: "Gears of War Theme" },
  { name: "Fallout 3 - Main Title Theme", search: "Fallout 3 Theme" },
  { name: "Borderlands - No Heaven", search: "Borderlands No Heaven" },
  { name: "Life is Strange - Obstacles", search: "Syd Matters Obstacles" },
  { name: "Hotline Miami - Hydrogen", search: "M O O N Hydrogen" },
  { name: "Team Fortress 2 - Main Theme", search: "Team Fortress 2 Theme" },
  { name: "Portal 2 - Want You Gone", search: "Portal 2 Want You Gone" },
  { name: "Fez - Adventure", search: "Fez Adventure Disasterpeace" },
  { name: "Shovel Knight - Strike the Earth!", search: "Shovel Knight Strike the Earth" },
  { name: "Celeste - Resurrections", search: "Celeste Resurrections Lena Raine" },
  { name: "Ori and the Blind Forest - Main Theme", search: "Ori and the Blind Forest Theme" },
  { name: "Cuphead - Floral Fury", search: "Cuphead Floral Fury" },
  { name: "Deltarune - Field of Hopes and Dreams", search: "Deltarune Field of Hopes and Dreams" },
  { name: "Payday 2 - Razormind", search: "Payday 2 Razormind" },
  { name: "Guilty Gear Xrd - Ride the Fire!", search: "Guilty Gear Ride the Fire" },
  { name: "Doom Eternal - The Only Thing They Fear Is You", search: "The Only Thing They Fear Is You Doom" },
  { name: "Devil May Cry 5 - Bury the Light", search: "Bury the Light Casey Edwards" },
  { name: "Metal Gear Rising - It Has To Be This Way", search: "It Has To Be This Way Metal Gear" },
  { name: "Street Fighter IV - Indestructible", search: "Street Fighter IV Indestructible" },
  { name: "Tekken 7 - Solitude", search: "Tekken 7 Solitude" },
  { name: "Super Mario World - Athletic Theme", search: "Super Mario World Athletic" },
  { name: "Zelda: Majora's Mask - Song of Healing", search: "Zelda Song of Healing" },
  { name: "Sonic Adventure - Open Your Heart", search: "Sonic Open Your Heart" },
  { name: "Sonic Heroes - Main Theme", search: "Sonic Heroes Theme" },
  { name: "Pokemon Diamond & Pearl - Route 209", search: "Pokemon Route 209" },
  { name: "Pokemon Ruby & Sapphire - Littleroot Town", search: "Pokemon Littleroot Town" },
  { name: "Animal Crossing: New Horizons - Title Theme", search: "Animal Crossing New Horizons Theme" },
  { name: "Wii Channel - Mii Plaza Theme", search: "Mii Plaza Theme" },
  { name: "Plague Inc. - Main Theme", search: "Plague Inc Theme" },
  { name: "Terraria - Overworld Day Theme", search: "Terraria Overworld Day" },
  { name: "Rayman Legends - Castle Rock", search: "Rayman Castle Rock" },
  { name: "Mirror's Edge - Still Alive", search: "Mirrors Edge Still Alive Lisa Miskovsky" },
  { name: "Half-Life - Hazardous Environments", search: "Half Life Hazardous Environments" },
  { name: "Half-Life 2 - CP Violation", search: "Half Life 2 CP Violation" },
  { name: "Death Stranding - BB's Theme", search: "Death Stranding BBs Theme Ludvig Forssell" },
  { name: "Grand Theft Auto V - Welcome to Los Santos", search: "GTA V Welcome to Los Santos" },
  { name: "Mass Effect 2 - Suicide Mission", search: "Mass Effect 2 Suicide Mission" },
  { name: "Alan Wake - Children of the Elder God", search: "Old Gods of Asgard Children of the Elder God" },
  { name: "Max Payne - Main Theme", search: "Max Payne Theme" },
  { name: "Splinter Cell: Chaos Theory - Theme", search: "Amon Tobin Chaos Theory" },
  { name: "Dead Space - Twinkle Twinkle Little Star", search: "Dead Space Twinkle Twinkle" },
  { name: "BioShock - Welcome to Rapture", search: "BioShock Welcome to Rapture" },
  { name: "BioShock Infinite - Will the Circle Be Unbroken", search: "Will the Circle Be Unbroken BioShock" },
  { name: "Dying Light - Main Theme", search: "Dying Light Theme" },
  { name: "The Witcher 3 - Lullaby of Woe", search: "Witcher 3 Lullaby of Woe" },
  { name: "Witcher 3 - Geralt of Rivia", search: "Witcher Geralt of Rivia theme" },
  { name: "Gothic II - Main Theme", search: "Gothic II Main Theme Kai Rosenkranz" },
  { name: "Age of Empires II - Main Theme", search: "Age of Empires II Theme" },
  { name: "Command & Conquer - Hell March", search: "Hell March Command Conquer" },
  { name: "StarCraft - Terran Theme 1", search: "StarCraft Terran Theme 1" },
  { name: "Diablo II - Tristram Theme", search: "Diablo Tristram Theme Matt Uelmen" },
  { name: "Baldur's Gate III - Main Theme", search: "Baldurs Gate 3 Theme Borislav Slavov" },
  { name: "Starfield - Main Theme", search: "Starfield Suite Inon Zur" },
  { name: "Fallout: New Vegas - Main Title", search: "Fallout New Vegas Theme" },
  { name: "Bloodborne - Ludwig, the Holy Blade", search: "Bloodborne Ludwig Theme" },
  { name: "Dark Souls - Gwyn, Lord of Cinder", search: "Dark Souls Gwyn Theme" },
  { name: "Sekiro - Ashina Reservoir Theme", search: "Sekiro Ashina Reservoir" },
  { name: "Hollow Knight - Hornet Theme", search: "Hollow Knight Hornet Christopher Larkin" },
  { name: "Katana Zero - Lorn", search: "Katana Zero Lorn" },
  { name: "Hotline Miami 2 - Roller Mobster", search: "Carpenter Brut Roller Mobster" },
  { name: "Furi - Make This Right", search: "The Toxic Avenger Make This Right" },
  { name: "Lethal Company - Icecream Music", search: "Lethal Company Icecream Music" },
  { name: "Phasmophobia - Lobby Theme", search: "Phasmophobia Lobby Music" },
  { name: "Valheim - Overture Theme", search: "Valheim Theme" },
  { name: "Subnautica - Abandon Ship", search: "Subnautica Abandon Ship Simon Chylinski" },
  { name: "Slay the Spire - Main Theme", search: "Slay the Spire Theme Clark Aboud" },
  { name: "Vampire Survivors - Library Theme", search: "Vampire Survivors Library" },
  { name: "Dead Cells - Prisoner's Quarters", search: "Dead Cells Prisoners Quarters" },
  { name: "Enter the Gungeon - Main Theme", search: "Enter the Gungeon Theme" },
  { name: "Spelunky 2 - Main Theme", search: "Spelunky 2 Theme Eirik Suhrke" },
  { name: "Amnesia: The Dark Descent - Main Theme", search: "Amnesia Dark Descent Theme" },
  { name: "Resident Evil - Safe Room Theme", search: "Resident Evil Safe Room Theme" },
  { name: "Resident Evil 4 - Save Theme", search: "Resident Evil 4 Serenity Save" },
  { name: "Silent Hill - Main Theme", search: "Silent Hill Theme Akira Yamaoka" },
  { name: "Apex Legends - Main Theme", search: "Apex Legends Theme" },
  { name: "Valorant - Main Menu Theme", search: "Valorant Main Menu Theme" },
  { name: "Counter-Strike: Global Offensive - Main Theme", search: "CS GO Main Theme" },
  { name: "Fortnite - OG Menu Music", search: "Fortnite OG Lobby Music" },
  { name: "Overwatch - Victory Theme", search: "Overwatch Victory Theme" },
  { name: "Destiny - The Traveler", search: "Destiny The Traveler Michael Salvatori" },
  { name: "Sea of Thieves - Bosun Bill", search: "Sea of Thieves Bosun Bill" },
  { name: "Left 4 Dead - Main Title", search: "Left 4 Dead Theme" },
  { name: "Garry's Mod - Toy Phone", search: "Garrys Mod Toy Phone" },

  // === 2. MOVIES, ANIME, TV SERIES & COMICS (150 TRACKS) ===
  { name: "Star Wars - The Imperial March", search: "Imperial March Star Wars" },
  { name: "Pirates of the Caribbean - He's a Pirate", search: "Hes a Pirate Pirates of the Caribbean" },
  { name: "Harry Potter - Hedwig's Theme", search: "Hedwigs Theme Harry Potter" },
  { name: "Lord of the Rings - Concerning Hobbits", search: "Concerning Hobbits Lord of the Rings" },
  { name: "Game of Thrones - Main Title", search: "Game of Thrones Theme" },
  { name: "Naruto - Sadness and Sorrow", search: "Sadness and Sorrow Naruto" },
  { name: "Dragon Ball Z - Cha-La Head-Cha-La", search: "Cha La Head Cha La" },
  { name: "Attack on Titan - Guren no Yumiya", search: "Guren no Yumiya" },
  { name: "Demon Slayer - Gurenge", search: "Gurenge Demon Slayer" },
  { name: "Neon Genesis Evangelion - A Cruel Angel's Thesis", search: "Cruel Angels Thesis" },
  { name: "Interstellar - Cornfield Chase", search: "Cornfield Chase Interstellar" },
  { name: "Titanic - My Heart Will Go On", search: "My Heart Will Go On Titanic" },
  { name: "The Avengers - Main Theme", search: "The Avengers Theme" },
  { name: "Indiana Jones - Raiders March", search: "Raiders March Indiana Jones" },
  { name: "Jurassic Park - Main Theme", search: "Jurassic Park Theme" },
  { name: "Naruto Shippuden - Blue Bird", search: "Blue Bird Naruto" },
  { name: "One Piece - We Are!", search: "We Are One Piece" },
  { name: "My Neighbor Totoro - Path of the Wind", search: "Path of the Wind Totoro" },
  { name: "Spirited Away - One Summer's Day", search: "One Summers Day Spirited Away" },
  { name: "The Godfather - Love Theme", search: "The Godfather Love Theme" },
  { name: "Back to the Future - Main Theme", search: "Back to the Future Theme" },
  { name: "Ghostbusters - Theme Song", search: "Ghostbusters Theme" },
  { name: "Sherlock - Opening Title", search: "Sherlock Opening Theme" },
  { name: "Doctor Who - Theme", search: "Doctor Who Theme" },
  { name: "Inception - Time", search: "Inception Time" },
  { name: "The Lion King - Circle of Life", search: "Circle of Life Lion King" },
  { name: "Gladiator - Now We Are Free", search: "Now We Are Free Gladiator" },
  { name: "Star Wars - Duel of the Fates", search: "Duel of the Fates Star Wars" },
  { name: "Naruto - Silhouette", search: "Silhouette Naruto" },
  { name: "Fullmetal Alchemist: Brotherhood - Again", search: "Again Fullmetal Alchemist" },
  { name: "Tokyo Ghoul - Unravel", search: "Unravel Tokyo Ghoul" },
  { name: "Dragon Ball GT - Dan Dan Kokoro Hikareteku", search: "Dan Dan Kokoro GT" },
  { name: "Death Note - L's Theme", search: "Death Note Ls Theme" },
  { name: "Hunter x Hunter - Departure!", search: "Departure Hunter x Hunter" },
  { name: "JoJo's Bizarre Adventure - Giorno's Theme", search: "Giornos Theme JoJo" },
  { name: "Sailor Moon - Moonlight Densetsu", search: "Moonlight Densetsu" },
  { name: "Howl's Moving Castle - Merry-Go-Round of Life", search: "Merry Go Round of Life Howls" },
  { name: "Princess Mononoke - Ashitaka and San", search: "Ashitaka and San Mononoke" },
  { name: "Stranger Things - Main Theme", search: "Stranger Things Theme" },
  { name: "The Pink Panther - Theme", search: "The Pink Panther Theme" },
  { name: "Mission: Impossible - Theme", search: "Mission Impossible Theme" },
  { name: "Spider-Man (1960s) - Theme", search: "Spider Man 1960s Theme" },
  { name: "The Simpsons - Opening Theme", search: "The Simpsons Theme" },
  { name: "Star Trek - Main Theme", search: "Star Trek Theme" },
  { name: "Cowboy Bebop - Tank!", search: "Cowboy Bebop Tank" },
  { name: "Shingeki no Kyojin - Shinzou wo Sasageyo", search: "Shinzou wo Sasageyo" },
  { name: "Pulp Fiction - Misirlou", search: "Pulp Fiction Misirlou" },
  { name: "The Matrix - Clubbed to Death", search: "Clubbed to Death Matrix" },
  { name: "Batman (1989) - Theme", search: "Batman 1989 Theme" },
  { name: "Breaking Bad - Main Title Theme", search: "Breaking Bad Theme" },
  { name: "Spider-Man: Raimi Trilogy - Main Title", search: "Spider Man Theme Danny Elfman" },
  { name: "The Dark Knight - Why So Serious?", search: "Why So Serious Dark Knight Hans Zimmer" },
  { name: "Star Wars - Cantina Band", search: "Cantina Band Star Wars" },
  { name: "Superman - Theme (1978)", search: "Superman Theme John Williams" },
  { name: "Mission Impossible - Ghost Protocol Theme", search: "Mission Impossible Ghost Protocol Theme" },
  { name: "James Bond 007 - Main Theme", search: "James Bond 007 Theme Monty Norman" },
  { name: "Pacific Rim - Main Theme", search: "Pacific Rim Theme Ramin Djawadi" },
  { name: "Iron Man 3 - Main Theme", search: "Iron Man 3 Theme Brian Tyler" },
  { name: "X-Men - Animated Series Theme", search: "X Men Animated Theme Ron Wasserman" },
  { name: "Marvel's Avengers - Earth's Mightiest Heroes", search: "Avengers Theme Alan Silvestri" },
  { name: "Gamera - Giant Monster Theme", search: "Gamera Theme" },
  { name: "Godzilla (1954) - Main Theme", search: "Godzilla Theme Akira Ifukube" },
  { name: "Doctor Who - I Am the Doctor", search: "I Am the Doctor Murray Gold" },
  { name: "Rick and Morty - Main Theme", search: "Rick and Morty Opening Theme Ryan Elder" },
  { name: "The Big Bang Theory - Theme Song", search: "Big Bang Theory Theme Barenaked Ladies" },
  { name: "The Office - Theme Song", search: "The Office Theme Song" },
  { name: "Friends - I'll Be There For You", search: "Ill Be There For You Friends Theme" },
  { name: "Gravity Falls - Main Theme", search: "Gravity Falls Theme Brad Breeck" },
  { name: "Pokemon (Anime) - Indigo League Theme", search: "Pokemon Theme Song Jason Paige" },
  { name: "Digimon Adventure - Butter-Fly", search: "Digimon Butterfly Koji Wada" },
  { name: "Dragon Ball - Makafushigi Adventure", search: "Makafushigi Adventure Dragon Ball" },
  { name: "One Piece - Bink's Sake", search: "Binks Sake One Piece" },
  { name: "Steins;Gate - Hacking to the Gate", search: "Hacking to the Gate Steins Gate" },
  { name: "Bleach - Asterisk", search: "Bleach Asterisk Orange Range" },
  { name: "Code Geass - Colors", search: "Colors Flow Code Geass" },
  { name: "Gurren Lagann - Sorairo Days", search: "Sorairo Days Gurren Lagann Shoko Nakagawa" },
  { name: "One Punch Man - The Hero!!", search: "The Hero One Punch Man JAM Project" },
  { name: "Sword Art Online - Crossing Field", search: "Crossing Field LiSA SAO" },
  { name: "Your Name - Zenzenzense", search: "Zenzenzense Radwimps Your Name" },
  { name: "A Silent Voice - Lit", search: "A Silent Voice Lit Kensuke Ushio" },
  { name: "Kill la Kill - Before My Body Is Dry", search: "Before My Body Is Dry Kill la Kill" },
  { name: "Fairy Tail - Main Theme", search: "Fairy Tail Main Theme Yasuharu Takanashi" },
  { name: "No Game No Life - This Game", search: "This Game Konomi Suzuki" },
  { name: "Death Note - The World", search: "Death Note The World Nightmare" },
  { name: "Mirai Nikki - Kuusou Mesorogiwi", search: "Kuusou Mesorogiwi Mirai Nikki" },
  { name: "Cowboy Bebop - The Real Folk Blues", search: "The Real Folk Blues Cowboy Bebop" },
  { name: "Erased - Re:Re:", search: "Erased Re Re Asian Kung Fu Generation" },
  { name: "Mob Psycho 100 - 99", search: "Mob Psycho 100 99 Theme" },
  { name: "Naruto Shippuden - Sign", search: "Sign Flow Naruto" },
  { name: "Bleach - Ranbu no Melody", search: "Ranbu no Melody Sid Bleach" },
  { name: "One Piece - Hikari E", search: "Hikari E One Piece" },
  { name: "Attack on Titan - Shinzou wo Sasageyo", search: "Shinzou wo Sasageyo Linked Horizon" },
  { name: "Boku no Hero Academia - The Day", search: "The Day Porno Graffitti Hero Academia" },
  { name: "Pokemon - Lugia's Song", search: "Pokemon Lugias Song Movie 2000" },
  { name: "Studio Ghibli - Town with an Ocean View", search: "Kikis Delivery Service Town with an Ocean View" },
  { name: "Spirited Away - Always With Me", search: "Spirited Away Always With Me Yumi Kimura" },
  { name: "Nausicaa of the Valley of the Wind - Opening Theme", search: "Nausicaa Theme Joe Hisaishi" },
  { name: "Monsters Inc. - Main Theme", search: "Monsters Inc Theme Randy Newman" },
  { name: "Toy Story - You've Got a Friend in Me", search: "Youve Got a Friend in Me Toy Story" },
  { name: "The Incredibles - Main Theme", search: "The Incredibles Theme Michael Giacchino" },
  { name: "Spider-Man: Into the Spider-Verse - Sunflower", search: "Post Malone Swae Lee Sunflower" },
  { name: "Up - Married Life", search: "Up Married Life Michael Giacchino" },
  { name: "Coco - Remember Me", search: "Remember Me Coco Miguel Natalia Lafourcade" },
  { name: "Ratatouille - Le Festin", search: "Le Festin Camille Ratatouille" },
  { name: "Star Wars - Rey's Theme", search: "Reys Theme Star Wars John Williams" },
  { name: "Harry Potter - Double Trouble", search: "Double Trouble Harry Potter John Williams" },
  { name: "Pirates of the Caribbean - Jack Sparrow Theme", search: "Jack Sparrow Theme Hans Zimmer" },
  { name: "The Hobbit - Misty Mountains Cold", search: "Misty Mountains Cold The Hobbit" },
  { name: "Game of Thrones - Light of the Seven", search: "Light of the Seven Ramin Djawadi" },
  { name: "Westworld - Main Title", search: "Westworld Theme Ramin Djawadi" },
  { name: "House of the Dragon - Main Theme", search: "House of the Dragon Theme Ramin Djawadi" },
  { name: "The Mandalorian - Main Theme", search: "The Mandalorian Theme Ludwig Goransson" },
  { name: "Loki - Main Theme", search: "Loki Green Theme Natalie Holt" },
  { name: "WandaVision - Agatha All Along", search: "Agatha All Along WandaVision" },
  { name: "Star Wars: The Clone Wars - Main Title", search: "Clone Wars Theme Kevin Kiner" },
  { name: "Avatar: The Last Airbender - Main Theme", search: "Avatar Last Airbender Theme Jeremy Zuckerman" },
  { name: "The Legend of Korra - Main Theme", search: "Legend of Korra Theme Jeremy Zuckerman" },
  { name: "Teen Titans - Main Theme", search: "Teen Titans Theme Puffy AmiYumi" },
  { name: "Ben 10 - Theme Song", search: "Ben 10 Theme Song Andy Sturmer" },
  { name: "Danny Phantom - Theme Song", search: "Danny Phantom Theme Song" },
  { name: "SpongeBob SquarePants - Main Title Theme", search: "SpongeBob SquarePants Theme" },
  { name: "Phineas and Ferb - Today Is Gonna Be a Great Day", search: "Phineas and Ferb Theme Bowling for Soup" },
  { name: "Scooby-Doo, Where Are You! - Theme", search: "Scooby Doo Where Are You Theme" },
  { name: "Looney Tunes - The Merry-Go-Round Broke Down", search: "Looney Tunes Theme" },
  { name: "Tom and Jerry - Main Theme", search: "Tom and Jerry Theme Scott Bradley" },
  { name: "Gravity Falls - Weirdmageddon Theme", search: "Gravity Falls Weirdmageddon" },
  { name: "Adventure Time - Main Theme", search: "Adventure Time Theme Song Ashley Eriksson" },
  { name: "Steven Universe - We Are the Crystal Gems", search: "Steven Universe Theme Rebecca Sugar" },
  { name: "Regular Show - Main Theme", search: "Regular Show Theme Mark Mothersbaugh" },
  { name: "The Amazing World of Gumball - Main Theme", search: "Gumball Theme Ben Locket" },
  { name: "Rick and Morty - Goodbye Moonmen", search: "Goodbye Moonmen Jemaine Clement" },
  { name: "Over the Garden Wall - Into the Unknown", search: "Into the Unknown Over the Garden Wall" },
  { name: "The Witcher (TV Show) - Toss a Coin to Your Witcher", search: "Toss a Coin to Your Witcher Joey Batey" },
  { name: "Stranger Things - Running Up That Hill", search: "Kate Bush Running Up That Hill Stranger Things" },
  { name: "Peaky Blinders - Red Right Hand", search: "Nick Cave Red Right Hand Peaky Blinders" },
  { name: "The Sopranos - Woke Up This Morning", search: "Woke Up This Morning Sopranos Theme Alabama 3" },
  { name: "Succession - Main Title Theme", search: "Succession Theme Nicholas Britell" },
  { name: "Twin Peaks - Main Theme", search: "Twin Peaks Theme Angelo Badalamenti" },
  { name: "Narcos - Tuyo", search: "Tuyo Rodrigo Amarante Narcos Theme" },
  { name: "Money Heist (La Casa de Papel) - My Life Is Going On", search: "My Life Is Going On Cecilia Krull" },
  { name: "La Casa de Papel - Bella Ciao", search: "Bella Ciao La Casa de Papel" },
  { name: "Squid Game - Way Back then", search: "Squid Game Way Back Then Jung Jae-il" },
  { name: "Better Call Saul - Main Theme", search: "Better Call Saul Theme Little Barrie" },
  { name: "Breaking Bad - Baby Blue", search: "Badfinger Baby Blue Breaking Bad" },
  { name: "Cowboy Bebop - Blue", search: "Cowboy Bebop Blue Yoko Kanno Mai Yamane" },
  { name: "Neon Genesis Evangelion - Fly Me to the Moon", search: "Fly Me to the Moon Claire Littley Evangelion" },
  { name: "Your Lie in April - Hikaru Nara", search: "Hikaru Nara Goose House" },
  { name: "Toradora! - Pre-Parade", search: "Pre Parade Toradora Opening" },
  { name: "Pokemon Theme - Double Trouble", search: "Team Rocket Double Trouble Theme Pokemon" },

  // === 3. POP, ROCK & LATIN WORLDWIDE HITS (150 TRACKS) ===
  { name: "Michael Jackson - Billie Jean", search: "Billie Jean Michael Jackson" },
  { name: "Queen - Bohemian Rhapsody", search: "Bohemian Rhapsody Queen" },
  { name: "Nirvana - Smells Like Teen Spirit", search: "Smells Like Teen Spirit Nirvana" },
  { name: "The Beatles - Yesterday", search: "The Beatles Yesterday" },
  { name: "Coldplay - Viva La Vida", search: "Viva La Vida Coldplay" },
  { name: "Daft Punk - Get Lucky", search: "Get Lucky Daft Punk" },
  { name: "Ed Sheeran - Shape of You", search: "Shape of You Ed Sheeran" },
  { name: "Billie Eilish - Bad Guy", search: "Bad Guy Billie Eilish" },
  { name: "Adele - Rolling in the Deep", search: "Rolling in the Deep Adele" },
  { name: "Bruno Mars - Uptown Funk", search: "Uptown Funk Bruno Mars Mark Ronson" },
  { name: "Eagles - Hotel California", search: "Hotel California Eagles" },
  { name: "Guns N' Roses - Sweet Child O' Mine", search: "Sweet Child O Mine Guns N Roses" },
  { name: "Bon Jovi - Livin' on a Prayer", search: "Livin on a Prayer Bon Jovi" },
  { name: "AC/DC - Back In Black", search: "Back In Black ACDC" },
  { name: "Linkin Park - In The End", search: "In The End Linkin Park" },
  { name: "A-ha - Take On Me", search: "Take On Me Aha" },
  { name: "Rick Astley - Never Gonna Give You Up", search: "Never Gonna Give You Up Rick Astley" },
  { name: "Luis Fonsi ft. Daddy Yankee - Despacito", search: "Despacito Luis Fonsi Daddy Yankee" },
  { name: "Shakira - Waka Waka", search: "Waka Waka Shakira" },
  { name: "Eminem - Lose Yourself", search: "Lose Yourself Eminem" },
  { name: "ABBA - Dancing Queen", search: "Dancing Queen ABBA" },
  { name: "Led Zeppelin - Stairway to Heaven", search: "Stairway to Heaven Led Zeppelin" },
  { name: "Pink Floyd - Another Brick in the Wall", search: "Another Brick in the Wall Pink Floyd" },
  { name: "David Bowie - Space Oddity", search: "Space Oddity David Bowie" },
  { name: "Rihanna - Umbrella", search: "Umbrella Rihanna" },
  { name: "Beyonce - Single Ladies", search: "Single Ladies Beyonce" },
  { name: "Lady Gaga - Bad Romance", search: "Bad Romance Lady Gaga" },
  { name: "Katy Perry - Roar", search: "Roar Katy Perry" },
  { name: "Taylor Swift - Shake It Off", search: "Shake It Off Taylor Swift" },
  { name: "Justin Bieber - Baby", search: "Baby Justin Bieber" },
  { name: "Sia - Chandelier", search: "Chandelier Sia" },
  { name: "Imagine Dragons - Radioactive", search: "Radioactive Imagine Dragons" },
  { name: "The Weeknd - Blinding Lights", search: "Blinding Lights The Weeknd" },
  { name: "Dua Lipa - Levitating", search: "Levitating Dua Lipa" },
  { name: "Olivia Rodrigo - Drivers License", search: "Drivers License Olivia Rodrigo" },
  { name: "Harry Styles - As It Was", search: "As It Was Harry Styles" },
  { name: "Miley Cyrus - Flowers", search: "Flowers Miley Cyrus" },
  { name: "Maroon 5 - Sugar", search: "Sugar Maroon 5" },
  { name: "One Direction - What Makes You Beautiful", search: "What Makes You Beautiful" },
  { name: "Avicii - Wake Me Up", search: "Wake Me Up Avicii" },
  { name: "Calvin Harris - Summer", search: "Summer Calvin Harris" },
  { name: "Gotye - Somebody That I Used To Know", search: "Somebody That I Used To Know Gotye" },
  { name: "Pharrell Williams - Happy", search: "Happy Pharrell Williams" },
  { name: "John Legend - All of Me", search: "All of Me John Legend" },
  { name: "Sam Smith - Stay With Me", search: "Stay With Me Sam Smith" },
  { name: "Hozier - Take Me To Church", search: "Take Me To Church Hozier" },
  { name: "Passenger - Let Her Go", search: "Let Her Go Passenger" },
  { name: "Bastille - Pompeii", search: "Pompeii Bastille" },
  { name: "Lorde - Royals", search: "Royals Lorde" },
  { name: "OneRepublic - Counting Stars", search: "Counting Stars OneRepublic" },
  { name: "Luis Miguel - Ahora Te Puedes Marchar", search: "Ahora Te Puedes Marchar Luis Miguel" },
  { name: "Soda Stereo - De Musica Ligera", search: "De Musica Ligera Soda Stereo" },
  { name: "Enanitos Verdes - Lamento Boliviano", search: "Lamento Boliviano Enanitos Verdes" },
  { name: "Maná - Oye Mi Amor", search: "Oye Mi Amor Mana" },
  { name: "Daddy Yankee - Gasolina", search: "Gasolina Daddy Yankee" },
  { name: "Bad Bunny - Dákiti", search: "Dakiti Bad Bunny Jhay Cortez" },
  { name: "Karol G - Tusa", search: "Tusa Karol G Nicki Minaj" },
  { name: "Rosalía - Malamente", search: "Malamente Rosalia" },
  { name: "Rauw Alejandro - Todo de Ti", search: "Todo de Ti Rauw Alejandro" },
  { name: "J Balvin ft. Willy William - Mi Gente", search: "Mi Gente J Balvin" },
  { name: "Don Omar - Danza Kuduro", search: "Danza Kuduro Don Omar" },
  { name: "Celia Cruz - La Vida Es Un Carnaval", search: "La Vida Es Un Carnaval Celia Cruz" },
  { name: "Marc Anthony - Vivir Mi Vida", search: "Vivir Mi Vida Marc Anthony" },
  { name: "Ricky Martin - Livin' La Vida Loca", search: "Livin La Vida Loca Ricky Martin" },
  { name: "Enrique Iglesias - Bailando", search: "Bailando Enrique Iglesias" },
  { name: "Chayanne - Torero", search: "Torero Chayanne" },
  { name: "Carlos Vives ft. Shakira - La Bicicleta", search: "La Bicicleta Carlos Vives Shakira" },
  { name: "Maluma - Felices los 4", search: "Felices los 4 Maluma" },
  { name: "Sebastian Yatra - Traicionera", search: "Traicionera Sebastian Yatra" },
  { name: "Camilo - Vida de Rico", search: "Vida de Rico Camilo" },
  { name: "Bizarrap ft. Quevedo - Bzrp Music Sessions, Vol. 52", search: "Quevedo Bzrp Music Sessions Vol 52" },
  { name: "Bizarrap ft. Shakira - Bzrp Music Sessions, Vol. 53", search: "Shakira Bzrp Music Sessions Vol 53" },
  { name: "Peso Pluma ft. Eslabon Armado - Ella Baila Sola", search: "Ella Baila Sola Eslabon Armado Peso Pluma" },
  { name: "Calle 13 - Atrévete-te-te", search: "Atrevete te te Calle 13" },
  { name: "Los Fabulosos Cadillacs - Matador", search: "Matador Los Fabulosos Cadillacs" },
  { name: "Molotov - Gimme The Power", search: "Gimme The Power Molotov" },
  { name: "Cafe Tacvba - Eres", search: "Eres Cafe Tacvba" },
  { name: "Juanes - A Dios Le Pido", search: "A Dios Le Pido Juanes" },
  { name: "Julieta Venegas - Limón y Sal", search: "Limon y Sal Julieta Venegas" },
  { name: "Natalia Lafourcade - Hasta la Raíz", search: "Hasta la Raiz Natalia Lafourcade" },
  { name: "Mon Laferte - Tu Falta De Querer", search: "Tu Falta De Querer Mon Laferte" },
  { name: "Jorge Drexler - Al Otro Lado del Río", search: "Al Otro Lado del Rio Jorge Drexler" },
  { name: "Fito Páez - 11 y 6", search: "11 y 6 Fito Paez" },
  { name: "Andrés Calamaro - Flaca", search: "Flaca Andres Calamaro" },
  { name: "Charly García - Nos Siguen Pegando Abajo", search: "Nos Siguen Pegando Abajo Charly Garcia" },
  { name: "Gustavo Cerati - Crimen", search: "Crimen Gustavo Cerati" },
  { name: "Los Prisioneros - Tren Al Sur", search: "Tren Al Sur Los Prisioneros" },
  { name: "Vilma Palma e Vampiros - Auto Rojo", search: "Auto Rojo Vilma Palma" },
  { name: "Bacilos - Caraluna", search: "Caraluna Bacilos" },
  { name: "Gente de Zona ft. Marc Anthony - La Gozadera", search: "La Gozadera Gente de Zona" },
  { name: "Michel Teló - Ai Se Eu Te Pego", search: "Ai Se Eu Te Pego Michel Telo" },
  { name: "Nicky Jam - El Perdón", search: "El Perdon Nicky Jam Enrique Iglesias" },
  { name: "Zion & Lennox - Pierdo la Cabeza", search: "Pierdo la Cabeza Zion Lennox" },
  { name: "Ozuna ft. Cardi B - La Modelo", search: "La Modelo Ozuna Cardi B" },
  { name: "Anuel AA ft. Daddy Yankee - China", search: "China Anuel AA Daddy Yankee" },
  { name: "Sh Shakira - Hips Don't Lie", search: "Hips Dont Lie Shakira Wyclef Jean" },
  { name: "Selena - Como la Flor", search: "Como la Flor Selena" },
  { name: "Gipsy Kings - Volare", search: "Volare Gipsy Kings" },
  { name: "Los Del Rio - Macarena", search: "Macarena Los Del Rio" },
  { name: "Kaoma - Lambada", search: "Lambada Kaoma" },
  { name: "Gloria Estefan - Conga", search: "Conga Gloria Estefan" },
  { name: "Santana ft. Rob Thomas - Smooth", search: "Smooth Santana Rob Thomas" },
  { name: "Los Lobos - La Bamba", search: "La Bamba Los Lobos" },
  { name: "Gente de Zona - Gozadera", search: "La Gozadera Gente de Zona" },
  { name: "Prince Royce - Darte un Beso", search: "Darte un Beso Prince Royce" },
  { name: "Romeo Santos - Propuesta Indecente", search: "Propuesta Indecente Romeo Santos" },
  { name: "Aventura - Obsesión", search: "Obsesion Aventura" },
  { name: "Tego Calderón - Pa' Que Retozen", search: "Pa Que Retozen Tego Calderon" },
  { name: "Don Omar - Dile", search: "Dile Don Omar" },
  { name: "Wis Wisin & Yandel - Rakata", search: "Rakata Wisin Yandel" },
  { name: "Ivy Queen - Quiero Bailar", search: "Quiero Bailar Ivy Queen" },
  { name: "Tito El Bambino - El Amor", search: "El Amor Tito El Bambino" },
  { name: "Farruko - Pepas", search: "Pepas Farruko" },
  { name: "Quevedo - Columbia", search: "Columbia Quevedo" },
  { name: "Myke Towers - LALA", search: "LALA Myke Towers" },
  { name: "Feid - Luna", search: "Luna Feid ATL Jacob" },
  { name: "El Alf Alfa - La Mamá de la Mamá", search: "La Mama de la Mama El Alfa" },
  { name: "Bad Bunny - Monaco", search: "Monaco Bad Bunny" },
  { name: "Karol G - Amargura", search: "Amargura Karol G" },
  { name: "Shakira ft. Fuerza Regida - El Jefe", search: "El Jefe Shakira Fuerza Regida" },
  { name: "Grupo Frontera ft. Bad Bunny - Un x100to", search: "Un x100to Grupo Frontera Bad Bunny" },
  { name: "Eslabon Armado - Ella Baila Sola", search: "Ella Baila Sola Eslabon Armado" },
  { name: "Fuerza Regida ft. Marshmello - Harley Quinn", search: "Harley Quinn Fuerza Regida Marshmello" },
  { name: "Natanael Cano - Amor Tumbado", search: "Amor Tumbado Natanael Cano" },
  { name: "Junior H - Y Lloro", search: "Y Lloro Junior H" },
  { name: "Christian Nodal - Adiós Amor", search: "Adios Amor Christian Nodal" },
  { name: "Carin León - Primera Cita", search: "Primera Cita Carin Leon" },
  { name: "Alejandro Fernández - Me Dediqué a Perderte", search: "Me Dedique a Perderte Alejandro Fernandez" },
  { name: "Luis Miguel - La Incondicional", search: "La Incondicional Luis Miguel" },
  { name: "Chayanne - Dejaría Todo", search: "Dejaria Todo Chayanne" },
  { name: "Ricardo Arjona - Fuiste Tú", search: "Fuiste Tu Ricardo Arjona Gaby Moreno" },
  { name: "Franco de Vita - Y Tú Te Vas", search: "Y Tu Te Vas Chayanne Franco de Vita" },
  { name: "Laura Pausini - En Cambio No", search: "En Cambio No Laura Pausini" },
  { name: "Jesse & Joy - ¡Corre!", search: "Corre Jesse Joy" },
  { name: "Camila - Mientes", search: "Mientes Camila" },
  { name: "Reik - Noviembre Sin Ti", search: "Noviembre Sin Ti Reik" },
  { name: "Sin Bandera - Entra En Mi Vida", search: "Entra En Mi Vida Sin Bandera" },
  { name: "Ha*Ash - Lo Aprendí de Ti", search: "Lo Aprendi de Ti Ha Ash" },
  { name: "La Oreja de Van Gogh - Rosas", search: "Rosas La Oreja de Van Gogh" },
  { name: "Estopa - Como Camarón", search: "Como Camaron Estopa" },
  { name: "Melendi - Destino o Casualidad", search: "Destino o Casualidad Melendi Ha Ash" },
  { name: "Alejandro Sanz - Corazón Partío", search: "Corazon Partio Alejandro Sanz" },
  { name: "Jarabe de Palo - La Flaca", search: "La Flaca Jarabe de Palo" },
  { name: "El Canto del Loco - Zapatillas", search: "Zapatillas El Canto del Loco" },
  { name: "Hombres G - Devuélveme a mi Chica", search: "Devuelveme a mi Chica Hombres G" },
  { name: "Miguel Bosé - Amante Bandido", search: "Amante Bandido Miguel Bose" },
  { name: "Los Rodríguez - Sin Documentos", search: "Sin Documentos Los Rodriguez" },
  { name: "Duncan Dhu - En Algún Lugar", search: "En Algun Lugar Duncan Dhu" },
  { name: "Alaska y Dinarama - A Quién Le Importa", search: "A Quien Le Importa Alaska Dinarama" },
  { name: "Mecano - Hijo de la Luna", search: "Hijo de la Luna Mecano" }
];

async function searchITunes(term, retries = 3) {
  const url = `https://itunes.apple.com/search?term=${encodeURIComponent(term)}&media=music&limit=1`;
  try {
    const response = await fetch(url);
    const text = await response.text();
    
    if (text.includes("Rate limit") || response.status === 403 || response.status === 429) {
      if (retries > 0) {
        console.log(`Rate limited for: ${term}. Retrying in 12 seconds... (${retries} retries left)`);
        await sleep(12000);
        return searchITunes(term, retries - 1);
      }
      return null;
    }
    
    const json = JSON.parse(text);
    if (json.results && json.results.length > 0) {
      const track = json.results[0];
      return track.previewUrl || null;
    }
  } catch (error) {
    console.error(`Error searching iTunes for: ${term}`, error.message);
    if (retries > 0) {
      console.log(`Retrying in 5 seconds...`);
      await sleep(5000);
      return searchITunes(term, retries - 1);
    }
  }
  return null;
}

async function run() {
  console.log(`Starting music extraction from iTunes API for ${songsList.length} tracks...`);
  const results = [];
  
  for (let i = 0; i < songsList.length; i++) {
    const song = songsList[i];
    console.log(`[${i+1}/${songsList.length}] Searching iTunes for: ${song.name}...`);
    
    const previewUrl = await searchITunes(song.search);
    await sleep(1500); // 1.5s delay to prevent Apple rate limits
    
    if (previewUrl) {
      // Find 3 incorrect song names from the list
      const pool = songsList.filter(s => s.name !== song.name);
      const incorrects = [];
      
      while (incorrects.length < 3 && pool.length > 0) {
        const randIdx = Math.floor(Math.random() * pool.length);
        const wrongSong = pool.splice(randIdx, 1)[0];
        incorrects.push(wrongSong.name);
      }
      
      const options = [song.name, ...incorrects];
      // Shuffle options
      for (let s = options.length - 1; s > 0; s--) {
        const r = Math.floor(Math.random() * (s + 1));
        const tmp = options[s];
        options[s] = options[r];
        options[r] = tmp;
      }
      
      results.push({
        id: i + 1,
        youtubeId: "", // Legacy support
        audioUrl: previewUrl, // Apple CDN streaming link
        options: options,
        answerIndex: options.indexOf(song.name)
      });
    } else {
      console.log(`WARNING: Preview URL not found for ${song.name}`);
    }
  }

  const fileContent = `// Archivo generado automáticamente con éxitos de la API de iTunes
export interface AudioQuestion {
  id: number;
  youtubeId: string;
  audioUrl?: string; // iTunes MP4/M4A direct link
  options: string[];
  answerIndex: number;
}

export const MUSIC_HITS_QUESTIONS: AudioQuestion[] = ${JSON.stringify(results, null, 2)};
`;

  // Write to Web
  fs.writeFileSync('e:/Imágenes/Tokkii/Web/src/data/MusicHitsQuestions.ts', fileContent);
  // Write to Builder
  fs.writeFileSync('E:/Imágenes/Tokkii/Builder_Tokkii/src/data/MusicHitsQuestions.ts', fileContent);
  
  console.log(`Done! Compiled ${results.length} questions.`);
}

run();
